# Generated by Django 2.0.6 on 2018-06-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='date_of_expiry',
            field=models.DateField(),
        ),
    ]
